### ISSUE TITLE
incorrect offset when landing to large docs

### ISSUE THREAD

**Issue by dwelle** [Thibaut/devdocs#455] opened 2016-08-08 20:03 UTC
If I search devdocs via url bar, e.g.: chrome -> `devdocs` -> <kbd>tab</kbd> -> `lodash assign` -> <kbd>enter</kbd>, it scroll to correct offset for `_.assign` docs, but then something else probably renders and viewport is offset about ~1-2 screens.

Doesn't happen for smaller docs (postgres etc.), nor when I search on-site (doesn't matter if the docs is rendered, or not).

~~Kinda can't repro directly [via link](http://devdocs.io/lodash~4/index#assign), unless when using a browser that doesn't have the docs loaded offline.~~ forgot I set `Scroll Anchoring` in my main browser.

**Comment by Thibaut** [comment] 2016-08-13 15:15
I can't reproduce even with scroll anchoring enabled.

Can you reproduce without scroll anchoring? If not, and you can reproduce with scroll anchoring enabled, I think it's a bug in Chrome.

Lodash's documentation has no images, so no reflows happen after the initial render. And when there are images, DevDocs actually has its own scroll anchoring.

**Comment by dwelle** [comment] 2016-08-14 08:02
I have explained myself incorrectly. The `scroll anchoring` was related to the crossed-out text only, not the main message. The bug occurs without `scroll anchoring`.

Clicking on [this link](http://devdocs.io/lodash~4/index#assign) causes the incorrect offset, but I now see it happens only in chrome (happens both for stable, and canary). Doesn't happen in FF.

**Comment by Thibaut** [comment] 2016-08-14 21:59
Should be fixed. Thanks for the bug report.

**Closed** 2016-08-14 21:58 UTC
Labels: bug

**Comment by dwelle** [comment] 2016-08-15 08:13
Yes it is. Thanks!
