### ISSUE TITLE
Offline mode is unavailable on I3 tiling window manager.

### ISSUE THREAD

**Issue by amirc** [Thibaut/devdocs#587] opened 2017-02-24 10:42 UTC
Hi,
I'm using Ubuntu 16 with google chrome. I used devdocs on my unity desktop env and everything worked perfect. Then I changed my windows manager to I3 and the offline mode stopped working.
I'm getting : 

> Offline mode is unavailable.
> DevDocs requires IndexedDB to cache documentations for offline access.
> Although your browser supports IndexedDB, DevDocs couldn't open the database.
> This could be because you're browsing in private mode or have disallowed offline storage on the domain.
> 

Because I know that IndexedDB works fine on my chrome I tried to fix the issue, but when I downloaded the sources and ran it locally on the I3 env, everything worked fine (offline mode was enabled).
So devdocs offline mode is not working for me only on production server when I use I3 tiling window manager.

Have any idea what could it be?

Thanks,
Amir.

**Comment by blittle** [comment] 2017-02-27 20:09
Offline mode is not working for me either. I also am running i3.

**Comment by Thibaut** [comment] 2017-03-01 13:32
Try to reset the app by running `app.reset()` in the console. If the issue persists, please run `indexedDB.open('docs')` in the console and post a screenshot of the result.

**Comment by blittle** [comment] 2017-03-01 16:23
This is what I get when I load the app with offline mode checked in the devtools:

![image](https://cloud.githubusercontent.com/assets/1566869/23469414/b8e2c552-fe60-11e6-88c7-186623945131.png)

**Comment by Thibaut** [comment] 2017-03-02 12:44
@blittle that's because you've checked "Disable cache". Uncheck that, reload once with connectivity, and it should work.

**Comment by blittle** [comment] 2017-03-02 16:13
Thanks!

**Comment by Thibaut** [comment] 2017-03-04 14:40
@blittle did the issue ever occur with the dev tools not opened?

@amirc could you confirm if your issue was also caused by having the dev tools opened with "Disable cache" turned on in the Network tab?

**Comment by amirc** [comment] 2017-03-04 19:16
@Thibaut I did app.reset(), and things solved out. now everything is working. Thanks.

**Comment by Thibaut** [comment] 2017-03-06 00:08
I've made improvements to the IndexedDB setup which I'm hoping will prevent this sort of issue (fixed by an `app.reset()`) from popping up in the future. Let me know if it happens again.

**Closed by Thibaut** 2017-03-06 00:08 UTC
Labels: bug, needs-info
