### ISSUE TITLE
Provide option to change keyboard shortcuts

### ISSUE THREAD

**Issue by dkjain** [Thibaut/devdocs#533] opened 2016-11-19 08:31 UTC
Hi,

Anyway to change / disable the Alt + arrow down/up shortcut to navigate right panel. Basically it's inconvenient to use both the hands when this can be operated single handedly.

If not possible in current repo, will you consider this for future releases.

thanks
dkj

**Comment by Thibaut** [comment] 2016-11-20 21:56
Duplicate of https://github.com/Thibaut/devdocs/issues/296.

**Closed by Thibaut** 2016-11-20 21:56 UTC

**Comment by saleo** [comment] 2022-04-09 11:41
would greatly appreciate if this can be implemented, thx a lot
