### ISSUE TITLE
OOPS, Offline mode is unavailable, I was using FireFox

### ISSUE THREAD

**Issue by richardtomkins** [Thibaut/devdocs#403] opened 2016-05-09 16:53 UTC
Below is a link to a 7 zip file containing a sequence of images that enhance the following description.

1. Using the Firefox Privacy setting, I cleared everything, cache, cookies, history, the whole thing.
2. Then I accessed DevDocs and added the various documentation packages I use.
3. Then I switched to offline mode and the error as above came up.
4. I added the Apache module, and accessed the offline mode, again the error.
5. I removed the Apache module and accessed the offline mode, this time no error.

The pictures are in squence so this text and the pictures should paint a picture that representes the fault I observed.

From Firefox Help - Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:46.0) Gecko/20100101 Firefox/46.0

https://drive.google.com/open?id=0B9tqoRtikQ5kfjlQajJWeC02RzJxSVkzXzh5cEVQTDJQOUhZMWJjYVRaSTFfbTRkQ3BJYkk

**Comment by eugenr2** [comment] 2016-05-16 16:59
Until today the app worked fine in offline mode. Today it was automatically upgraded and now in offline mode it says: "The app failed to load. Check your internet connection and try reloading". If I connect to internet the app works. In firefox it doesn't work at all. In chrome it stops working at random times. It seems that typing by hand another url (if it's devdocs.io I change to devdocs.io/offline) in the browser's adress bar makes the app working again for some time.

Browsers: Chrome 49, Firefox 46,  OS:Android 4.4.2

**Comment by superkresek** [comment] 2016-05-17 16:06
i've got same problem here with firefox dev edition 48.0a2. i have tried resetting firefox configuration but i did not succesfully access devdocs.io offline mode.

**Comment by Thibaut** [comment] 2016-05-18 12:12
@eugenr2 your issue was caused by a change I introduced a couple weeks ago and fixed by https://github.com/Thibaut/devdocs/commit/719460f3b4610351fb5a64af489e08f3d3d4320b (just deployed). Sorry about that, and thanks for the bug report.

@richardtomkins your issue is different and unfortunately I'm unable to replicate. Could you open the dev tools and take a screenshot of this view please:

![devdocs api documentation 2016-05-18 08-10-15](https://cloud.githubusercontent.com/assets/17579/15357970/08ddaaea-1cd0-11e6-8c97-99950f5d3560.png)

**Comment by richardtomkins** [comment] 2016-05-18 15:22
OK, here is the information.

I will restate, 64 bit Firefox, I clear all the history.
I open DevDocs and add the various documents I use.
I click on Offline and get the error attributed to Chrome.
I add Apache.
I remove Apache.
I access Offline again and it works.

**Comment by Thibaut** [comment] 2016-05-28 14:25
> get the error attributed to Chrome

I'm not sure what this means. Could you take a screenshot please?

Also please post a screenshot of the dev tools in [this view](https://github.com/Thibaut/devdocs/issues/403#issuecomment-220007653) when the offline page doesn't work.

**Comment by Thibaut** [comment] 2016-07-03 22:50
Can't fix without more info (https://github.com/Thibaut/devdocs/issues/403#issuecomment-222311188).

**Closed by Thibaut** 2016-07-03 22:50 UTC
Labels: needs-info

**Comment by richardtomkins** [comment] 2016-07-03 23:41
I just don't have the time to work on this.

**Comment by ZashIn** [comment] 2016-08-11 15:28
Same problem here:

Firefox 48.0 x64 @ Windows 10
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:48.0) Gecko/20100101 Firefox/48.0

1. with fresh profile download offline data (all default)
2. clear all browser data
3. reopen https://devdocs.io/offline
=> "Offline mode is unavailable"

The problem also appears after restart of Firefox.

Here are some pics. Tell me if you need more info (logs, ... )

- offline with storage toolbar  / Indexed DB
![1-offline_with_storage_cropped](https://cloud.githubusercontent.com/assets/10155187/17594219/c6cbe688-5fe8-11e6-9748-1c9d9d707625.png)
- docs
![2-docs](https://cloud.githubusercontent.com/assets/10155187/17593699/118b8018-5fe7-11e6-86c3-a7bc1881f87e.png)
- css
![3-css](https://cloud.githubusercontent.com/assets/10155187/17593701/1193cb74-5fe7-11e6-853c-1f0bf39458d7.png)
- javascript
![4-javascript](https://cloud.githubusercontent.com/assets/10155187/17593700/118d1266-5fe7-11e6-8b3e-d84e48231b43.png)
- Local Storage
![5-local_storage](https://cloud.githubusercontent.com/assets/10155187/17593698/1181b24a-5fe7-11e6-86f6-63207b261120.png)
- Cookies
![6-cookies](https://cloud.githubusercontent.com/assets/10155187/17593702/119b8256-5fe7-11e6-8e84-2d9eaffa3ff8.png)

**Comment by Thibaut** [comment] 2016-08-13 16:33
@ZashIn Thanks a lot for the screenshots. It seems you're missing the`schema` cookie. Without it, the app will try to open the IDB database with a version number that doesn't match the one in IDB. 

Could you run `Cookies.get('schema')` in the console. If you get nothing, try running `Cookies.set('schema', '10', path: '/', expires: 1e8)`, and see if you get an error.

**Comment by ZashIn** [comment] 2016-08-14 13:57
@Thibaut Thank you, the cookie was the problem, indeed:
`Cookies.get('schema')` returned nothing = no cookie.
With `Cookies.set('schema', '10', {path: '/', expires: 1e8})` (you missed the braces for the third argument) the offline feature works again.
So this problem probably comes down to my cookie settings: I forgot the exception from the session cookies ;)

**Comment by Thibaut** [comment] 2016-08-14 16:50
@ZashIn it's still weird that the app managed to save other cookies, but not the `schema` one. They all use the same options. What do you mean by:

>  I forgot the exception from the session cookies

**Comment by ZashIn** [comment] 2016-08-15 12:03
I am using firefox with session cookies = delete cookies when closing firefox.
But I was wrong anyway, that cannot be the source of the problem, since I tested it on a fresh profile with default cookie settings (keep until they expire).

After further testing, it seems like the sheme cookie is only set after downloading all the (default) offline content. It is not set when I download just one or a few decumentations, but I am not sure when exacly it is set.
So if the cookie is required for IDB database but only set when creating / downloading the database, then deleting the cookies without (fully) clearing the database leads to a corrupted state, as you said, right?:

> the app will try to open the IDB database with a version number that doesn't match the one in IDB.

**Comment by Thibaut** [comment] 2016-08-20 18:27
The `schema` cookie is only set (the first time) and incremented after certain actions (enabling/disabling docs, clicking "Install all"). Its presence isn't required if you haven't performed those actions yet. I'll try to add logging in the code that sets the cookie, to detect when it isn't saved properly.

**Comment by metamaker** [comment] 2017-01-03 13:17
I had same issue 2 days ago. Executing `Cookies.set('schema', '10', {path: '/', expires: 1e8})` helped solve problem in my browser (Firefox 50.1.0, Linux). Not fixed yet.
