### ISSUE TITLE
Offline dark theme

### ISSUE THREAD

**Issue by mdh34** [Thibaut/devdocs#745] opened 2018-01-10 19:42 UTC
While offline, dark theme options aren't respected
Steps to reproduce:

- Go offline
- enable dark theme in preferences
- reload page

The page just defaults back to the white theme on a reload
tested on chrome 64 beta and using webkit2

It looks like a problem with the application cache - perhaps the settings or dark css aren't cached fully?

**Comment by Thibaut** [comment] 2018-03-24 14:01
Duplicate of #745.

**Closed by Thibaut** 2018-03-24 14:01 UTC

**Comment by mdh34** [comment] 2018-03-24 14:14
#745 is this issue

**Comment by Thibaut** [comment] 2018-03-24 14:14
Oops. I meant #613.

**Comment by mdh34** [comment] 2018-03-24 14:30
Ah :)

**Comment by j-f1** [comment] 2018-03-24 21:07
Duplicate of #613
