### ISSUE TITLE
OPTIONS http://docs.devdocs.io/ empty response

### ISSUE THREAD

**Issue by zg** [Thibaut/devdocs#264] opened 2015-09-11 14:32 UTC
<img width="1267" alt="screen shot 2015-09-11 at 10 32 14" src="https://cloud.githubusercontent.com/assets/407905/9817369/6d0357e2-5870-11e5-96da-5a75cebf69c8.png">

**Comment by Thibaut** [comment] 2015-09-12 14:37
Could you paste the output of in the terminal:
```
curl 'http://docs.devdocs.io/html/db.json' -X OPTIONS -H 'Origin: http://devdocs.io' -H 'Access-Control-Request-Method: GET' -H 'Access-Control-Request-Headers: x-requested-with' -v
```

**Comment by zg** [comment] 2015-09-12 14:48
```
$ curl 'http://docs.devdocs.io/html/db.json' -X OPTIONS -H 'Origin: http://devdocs.io' -H 'Access-Control-Request-Method: GET' -H 'Access-Control-Request-Headers: x-requested-with' -v
* Hostname was NOT found in DNS cache
*   Trying 198.232.125.3...
* Connected to docs.devdocs.io (127.0.0.1) port 80 (#0)
> OPTIONS /html/db.json HTTP/1.1
> User-Agent: curl/7.37.1
> Host: docs.devdocs.io
> Accept: */*
> Origin: http://devdocs.io
> Access-Control-Request-Method: GET
> Access-Control-Request-Headers: x-requested-with
> 
* Empty reply from server
* Connection #0 to host docs.devdocs.io left intact
curl: (52) Empty reply from server
```

**Comment by Thibaut** [comment] 2015-09-12 14:52
What about:
```
curl -I 'http://docs.devdocs.io/html/db.json'
```

**Comment by zg** [comment] 2015-09-12 14:59
```
$ curl -I "http://docs.devdocs.io/html/db.json"
HTTP/1.1 200 OK
Date: Sat, 12 Sep 2015 14:59:23 GMT
Content-Type: application/json
Content-Length: 1923634
Connection: keep-alive
Last-Modified: Mon, 27 Jul 2015 02:54:58 GMT
ETag: "6896f492e689782fb85ab2021cb2544b"
Server: NetDNA-cache/2.2
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, OPTIONS
Access-Control-Max-Age: 86400
Access-Control-Allow-Credentials: true
Vary: Accept-Encoding, Origin, Access-Control-Request-Headers, Access-Control-Request-Method
Expires: Sun, 13 Sep 2015 14:59:23 GMT
Cache-Control: max-age=86400
X-Cache: MISS
Accept-Ranges: bytes
```

**Comment by Thibaut** [comment] 2015-09-12 15:15
And:

```
curl -I "http://docs.devdocs.io/html/db.json" -v
```

**Comment by zg** [comment] 2015-09-12 15:31
```
$ curl -I "http://docs.devdocs.io/html/db.json" -v
* Hostname was NOT found in DNS cache
*   Trying 198.232.125.3...
* Connected to docs.devdocs.io (127.0.0.1) port 80 (#0)
> HEAD /html/db.json HTTP/1.1
> User-Agent: curl/7.37.1
> Host: docs.devdocs.io
> Accept: */*
> 
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Date: Sat, 12 Sep 2015 15:31:42 GMT
Date: Sat, 12 Sep 2015 15:31:42 GMT
< Content-Type: application/json
Content-Type: application/json
< Content-Length: 1923634
Content-Length: 1923634
< Connection: keep-alive
Connection: keep-alive
< Last-Modified: Mon, 27 Jul 2015 02:54:58 GMT
Last-Modified: Mon, 27 Jul 2015 02:54:58 GMT
< ETag: "6896f492e689782fb85ab2021cb2544b"
ETag: "6896f492e689782fb85ab2021cb2544b"
< Accept-Ranges: bytes
Accept-Ranges: bytes
* Server NetDNA-cache/2.2 is not blacklisted
< Server: NetDNA-cache/2.2
Server: NetDNA-cache/2.2
< Access-Control-Allow-Origin: *
Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET, OPTIONS
Access-Control-Allow-Methods: GET, OPTIONS
< Access-Control-Max-Age: 86400
Access-Control-Max-Age: 86400
< Access-Control-Allow-Credentials: true
Access-Control-Allow-Credentials: true
< Vary: Accept-Encoding, Origin, Access-Control-Request-Headers, Access-Control-Request-Method
Vary: Accept-Encoding, Origin, Access-Control-Request-Headers, Access-Control-Request-Method
< Expires: Sun, 13 Sep 2015 15:31:42 GMT
Expires: Sun, 13 Sep 2015 15:31:42 GMT
< Cache-Control: max-age=86400
Cache-Control: max-age=86400
< X-Cache: MISS
X-Cache: MISS

< 
* Connection #0 to host docs.devdocs.io left intact
```

**Comment by Thibaut** [comment] 2015-09-12 15:51
`Connected to docs.devdocs.io (127.0.0.1) port 80 (#0)`

This sounds like an issue with your computer (routing everything through `127.0.0.1` and blocking `OPTIONS` requests), or MaxCDN. I've contacted MaxCDN in case the issue is on their end.

**Comment by zg** [comment] 2015-09-12 15:54
```
$ cat /etc/hosts | grep 198.232.125.3
$
```

I'm not sure how to block OPTIONS requests, so I'm assuming that they aren't blocked.

**Comment by Thibaut** [comment] 2015-09-12 15:57
It could be a web server or proxy running in the background.

**Comment by zg** [comment] 2015-09-12 15:58
I don't have either of those running on my laptop.

**Comment by miohtama** [comment] 2015-09-12 16:50
Try with `https://devdocs.io/` - because it is HTTP connection, there is a possibility that your ISP is tampering with your traffic.

Also try from another internet connection with possible. Or another computer on the same connection.

**Comment by zg** [comment] 2015-09-12 16:51
I ran into the same issue using TWC or my university network.

**Comment by Thibaut** [comment] 2015-09-13 19:49
What does this give you:
```
curl 'http://www.google.com' -X OPTIONS -v -o /dev/null -s
```

**Comment by zg** [comment] 2015-09-13 19:53
```
$ curl 'http://www.google.com' -X OPTIONS -v -o /dev/null -s         
* Rebuilt URL to: http://www.google.com/
* Hostname was NOT found in DNS cache
*   Trying 216.58.216.100...
* Connected to www.google.com (127.0.0.1) port 80 (#0)
> OPTIONS / HTTP/1.1
> User-Agent: curl/7.37.1
> Host: www.google.com
> Accept: */*
> 
* Empty reply from server
* Connection #0 to host www.google.com left intact
```

Interesting.

**Comment by Thibaut** [comment] 2015-09-13 20:01
So there is definitely something running on your computer that's tampering with the network, and breaking `OPTIONS` requests (you should have received a "405 Method Not Allowed" response from Google).

This will cause all sites that use CORS to break — not just DevDocs.

Closing this issue since there isn't anything I/we can do on DevDocs's end.

**Closed by Thibaut** 2015-09-13 20:01 UTC

**Comment by Thibaut** [comment] 2015-09-13 20:15
FYI someone reported the same issue to me privately and fixed it by uninstalling "Xtreme Download Manager".

**Comment by zg** [comment] 2015-09-13 20:16
I don't have any software like that on my system, but I am suspicious that something might be maliciously running in the background that I'm not aware of.

**Comment by zg** [comment] 2015-09-13 20:51
I had Cisco AnyConnect (a VPN software) somehow remaining on my system.

First run: `sudo lsof -i :80`

Then check what process ran the VPN: `ps aux | grep <pid from previous command>`

**Comment by n370** [comment] 2015-09-15 15:59
@zg somehow ```sudo lsof -i :80``` outputs nothing for me. I then did ```ps aux | grep cisco``` and got the following:

```
dylson           1060   0.9  0.0  2441988    688 s000  S+   10:59AM   0:00.00 grep cisco
root              337   0.0  0.0   711408   6860   ??  S    10:24AM   0:00.90 /opt/cisco/anyconnect/bin/acwebsecagent -console
root               52   0.0  0.0   706672   7300   ??  Ss   10:24AM   0:00.97 /opt/cisco/anyconnect/bin/vpnagentd -execv_instance
```

Killing those processes isn't straightforward and hacking with the spotlight lead me to an uninstall script located in this path ```/opt/cisco/anyconnect/bin/anyconnect_uninstall.sh```

I executed it and got fixed the issue I reported [here](https://groups.google.com/d/topic/devdocs/4ZVgzXRNoGs/discussion). Thanks @Thibaut

**Comment by zg** [comment] 2015-09-15 16:06
Cisco AnyConnect is not a trojan, it's a product for connecting to a VPN.

On Tuesday, September 15, 2015, Dylson Valente Neto <
notifications@github.com> wrote:

> @zg <https://github.com/zg> somehow sudo lsof -i :80 outputs nothing for
> me. I then did ps aux | grep cisco and got the following:
>
> dylson           1060   0.9  0.0  2441988    688 s000  S+   10:59AM   0:00.00 grep cisco
> root              337   0.0  0.0   711408   6860   ??  S    10:24AM   0:00.90 /opt/cisco/anyconnect/bin/acwebsecagent -console
> root               52   0.0  0.0   706672   7300   ??  Ss   10:24AM   0:00.97 /opt/cisco/anyconnect/bin/vpnagentd -execv_instance
>
> Killing those processes isn't straightforward and hacking with the
> spotlight lead me to an uninstall script located in this path
> /opt/cisco/anyconnect/bin/anyconnect_uninstall.sh
>
> I executed it and got fixed the issue I reported here
> <https://groups.google.com/d/topic/devdocs/4ZVgzXRNoGs/discussion>.
> Thanks @Thibaut <https://github.com/Thibaut>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Thibaut/devdocs/issues/264#issuecomment-140442141>.
>


-- 
Sent from my mobile device

**Comment by n370** [comment] 2015-09-15 16:56
@zg I don't wan't this discussion to go too far but could you then explain me why it has to be such a persistent and obscure process that I can't stop easily with the standard tools available. And why it hooks to my browser tcp connections without giving me a clue about that. Forgive me my ignorance if that's what VPN connection solutions are supposed to do.

**Comment by zg** [comment] 2015-09-15 16:58
That's what VPN software is supposed to do. :) It's supposed to sort of
"mask" your connection to the Internet so that you can browse without
people knowing your real location.

On Tuesday, September 15, 2015, Dylson Valente Neto <
notifications@github.com> wrote:

> @zg <https://github.com/zg> I don't wan't this discussion to go too far
> but could you then explain me why it has to be such a persistent and
> obscure process that I can't stop easily with the standard tools available.
> And why it hooks to my browser tcp connections without giving me a clue
> about that. Forgive me my ignorance if that's what VPN connection solutions
> are supposed to do.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Thibaut/devdocs/issues/264#issuecomment-140461977>.
>


-- 
Sent from my mobile device

**Comment by n370** [comment] 2015-09-15 17:19
@zg  LOL it's weird that it does it for Firefox only. You should've seen my ```lsof``` output. Well, whatever. Issue solved for me. I can't complain too much because in the end I'm still working on a proprietary, closed source system. I'll get back to you when I start typing on a GNU/Linux box.

**Comment by acca** [comment] 2015-12-04 08:35
Cisco anyConnect was the cause in my case. Just uninstalled and re-installed without the "Web Security" module. Here the suggestion followed: http://www.bennadel.com/blog/2559-cisco-anyconnect-vpn-client-may-block-cors-ajax-options-requests.htm.

**Comment by n370** [comment] 2015-12-07 17:25
Now that alleviates my angry @acca. Great addition to this thread.
