### ISSUE TITLE
Offline mode is unavailable. Firefox 52 & 54

### ISSUE THREAD

**Issue by scheinercc** [Thibaut/devdocs#599] opened 2017-03-22 04:06 UTC
Hi,
I have issues with the offline mode in current Firefox Dev Edition (v54) and stable (v52) with two separate profiles (so likely not #508). It does work with the current Nightly (v55).

In the console I see this error:
`IDB error DOMError{ name: "UnknownError", message: "The operation failed for reasons unrelated to the database itself and not covered by any other error code." }`

In v54 I tried the steps from #587. 
`app.reset()`
=> `unknown`

`indexedDB.open('docs')`
=> `IDBOpenDBRequest { onblocked: null, onupgradeneeded: null, source: null, transaction: null, readyState: "pending", onsuccess: null, onerror: null }`
=> `UnknownError`

ok, reloading now I also get this security error:
`Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src https://devdocs.io 'nonce-devdocs' http://cdn.devdocs.io https://cdn.devdocs.io https://www.google-analytics.com https://secure.gaug.es http://*.jquery.com https://*.jquery.com”). Source: ;(function installGlobalHook(window) {
 ....`

**Comment by Thibaut** [comment] 2017-04-23 13:39
Closing as duplicate of #584. This seems to be an issue in Firefox, but I've yet to pin down the cause (unable to replicate, even though I use Firefox daily). I'm planning to do more research in the coming weeks.

The security error is unrelated. An addon or proxy is trying to inject/run JS on the page, which DevDocs's CSP is blocking.

**Closed by Thibaut** 2017-04-23 13:39 UTC
